<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>baseline_test_ALL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ad76b806-21d1-4982-b53e-7b8c0701c807</testSuiteGuid>
   <testCaseLink>
      <guid>da7c3905-d898-40d9-be70-4eba4def1739</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/KatalonicsBlog/Visual Test Cases/Baseline Analysis</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>84806ab6-a88e-438f-8de5-aac2aa8be52e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/All Location Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>84806ab6-a88e-438f-8de5-aac2aa8be52e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>componentName</value>
         <variableId>e1487eaf-633d-4b71-b89b-49da1b3d6eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>84806ab6-a88e-438f-8de5-aac2aa8be52e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>componentLocation</value>
         <variableId>5e6dfab3-1130-47a7-8d7f-f06d40a12ceb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>84806ab6-a88e-438f-8de5-aac2aa8be52e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>acceptableDiff</value>
         <variableId>246fabd7-93dd-4cab-b735-633509d748a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6566affb-1d7d-42b9-90ad-f5544b333be0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f68ec8a7-4233-4a05-9fae-7d4aefc34be8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
