<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create_baseline_image</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f8ef12ae-bd7f-4dd0-994c-80292cf78ebf</testSuiteGuid>
   <testCaseLink>
      <guid>e6d4d288-58a5-4e9b-84e8-6af81426803f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/KatalonicsBlog/Visual Test Cases/Create Baseline Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1487eaf-633d-4b71-b89b-49da1b3d6eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e6dfab3-1130-47a7-8d7f-f06d40a12ceb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>246fabd7-93dd-4cab-b735-633509d748a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebaf7b21-dea3-41a2-8d87-b8648300d516</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
